export enum SortCriteria {
    POPULARITY_DESC = "popularity.desc",
    POPULARITY_ASC = "popularity.asc",
    RELEASE_DATE_DESC = "release_date.desc",
    RELEASE_DATE_ASC = "release_date.asc",
    REVENUE_DESC = "revenue.desc",
    REVENUE_ASC = "revenue.asc",
    PRIMARY_RELEASE_DATE_DESC = "primary_release_date.desc",
    PRIMARY_RELEASE_DATE_ASC = "primary_release_date.asc",
    ORIGINAL_TITLE_DESC = "original_title.desc",
    ORIGINAL_TITLE_ASC = "original_title.asc",
    VOTE_AVERAGE_DESC = "vote_average.desc",
    VOTE_AVERAGE_ASC = "vote_average.asc",
    VOTE_COUNT_DESC = "vote_count.desc",
    VOTE_COUNT_ASC = "vote_count.asc",
}
